import { expect, test } from "vitest";
import { SymmetricGroupOf } from "../groups/symmetric";
import { Group } from "../types/group";
import { fromCycles, inverseOfPermutation, multiply, toCycleString } from "../groups/permutation";
import { fromGenerator, printTable } from "../groups/group";
import { DihedralGroupOfOrder } from "../groups/dihedral";
import { centerOf, firstSubgroupTheorem, isNormalSubgroup, secondSubgroupTheorem } from "../groups/subgroup";

test('Subgroups', () => {
  const S3 = SymmetricGroupOf(3);

  const sub_items = [
    '(1,2,3)',
    '(1,3,2)',
    '',
  ]
  const sub_mul = (a: string, b: string) => toCycleString(multiply(fromCycles(a), fromCycles(b)))

  const sub_inverse = inverseOfPermutation
  const sub_e = '';
  const subS3: Group<string> = {
    e: sub_e,
    inverse: sub_inverse,
    mul: sub_mul,
    set: sub_items
  }

  printTable(subS3)

  expect(firstSubgroupTheorem(S3, sub_items)).toBe(true)
  expect(secondSubgroupTheorem(S3, sub_items)).toBe(true)
  expect(isNormalSubgroup(S3, sub_items)).toBe(true)
})

test('Subgroup of rotations of an n-gon is normal in dihedral group Dn', () => {
  const D4 = DihedralGroupOfOrder(8);
  const sub_items = ['', 'r', 'rr', 'rrr']

  expect(firstSubgroupTheorem(D4, sub_items)).toBe(true)
  expect(secondSubgroupTheorem(D4, sub_items)).toBe(true)
  expect(isNormalSubgroup(D4, sub_items)).toBe(true)
})

test('The subgroup of S3 generated by the transposition (12) is not normal', () => {
  const S3 = SymmetricGroupOf(3)
  const H = fromGenerator(['(1,2)'], S3.mul, S3.inverse)
  
  printTable(H)

  expect(firstSubgroupTheorem(S3, H.set)).toBe(true)
  expect(secondSubgroupTheorem(S3, H.set)).toBe(true)
  expect(isNormalSubgroup(S3, H.set)).toBe(false)
})

test('Center', () => {
  const D4 = DihedralGroupOfOrder(8)
  const center = centerOf(D4)

  expect(center).toMatchObject(['', 'rr'])
})

test('The center of the symmetric group, Sn, is trivial for n ≥ 3', () => {
  const S3 = SymmetricGroupOf(3)
  const centerOfS3 = centerOf(S3)

  expect(centerOfS3).toMatchObject([''])
  
  const S4 = SymmetricGroupOf(4)
  const centerOfS4 = centerOf(S4)
  
  expect(centerOfS4).toMatchObject([''])
})
